### ISSUE TITLE
Witch rust version?

### ISSUE THREAD

**Issue by ComputeShader** [syzygy1/Rustfish#3]
I got some immutable/mutable borrow errors and deprecated wearnings.
Witch rust compiler version is used in this project?

**Comment by syzygy1** [comment]
A very old one, I'm afraid. The one that was current at the time of the last commit, which was March 2018.
I may have a look into fixing the problems when I find time.

**Comment by syzygy1** [comment]
I think it should now compile with current rustc (I have 1.44.0 here).
