### ISSUE TITLE
Shift right would overflow

### ISSUE THREAD

**Issue by sengerts** [syzygy1/Rustfish#4]
I am getting the following errors in the bitboard module while compiling the source code:
![image](https://user-images.githubusercontent.com/5702543/100222336-3af93d80-2f1a-11eb-97b9-ccddb92041e7.png)

The code affected by these errors is the following:
``` rust
// Compute the attack's index using the 'magic bitboards' approach
fn index_bishop(s: Square, occupied: Bitboard) -> usize {
    unsafe {
        u64::wrapping_mul((occupied & BISHOP_MAGICS.masks[s.0 as usize]).0,
            BISHOP_MAGICS.magics[s.0 as usize]) as usize >> (64-9)
    }
}

fn index_rook(s: Square, occupied: Bitboard) -> usize {
    unsafe {
        u64::wrapping_mul((occupied & ROOK_MAGICS.masks[s.0 as usize]).0,
            ROOK_MAGICS.magics[s.0 as usize]) as usize >> (64-12)
    }
}
```

Do you know why this error occurs or what I can do to fix the overflow?

**Comment by sengerts** [comment]
Can I jsut use a wrapping_shr on the usize value or will this differ from the intended semantics?

**Comment by niklasf** [comment]
Looks like `usize` has less than 64 bits on your platform. The intention is to do the shift first in `u64`, then cast to usize:

```rust
(u64::wrapping_mul(
    (occupied & ROOK_MAGICS.masks[s.0 as usize]).0,
    ROOK_MAGICS.magics[s.0 as usize]
) >> (64-12)) as usize
```

**Comment by syzygy1** [comment]
Yes, this looks like a bug, and @niklasf 's fix seems correct.

**Comment by sengerts** [comment]
Thank you both! I have forked the repo and created a pull request.
