### ISSUE TITLE
Compile errors due to most recent commit

### ISSUE THREAD

**Issue by amberjhu** [syzygy1/Rustfish#6]
Hi, I just tried building fresh from source with `cargo build --release` and it failed to compile due to the most recent commit. When I compiled from the parent (c5cdb...) it worked fine

**Comment by syzygy1** [comment]
Which version of Rust are you using?
$ rustc --version
rustc 1.48.0

**Comment by amberjhu** [comment]
Ah, I see I was on 1.44.1

Sorry! I didn't think that they would have fixed a borrow checker error in the past couple months
